version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres

    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres
    restart: always

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"

#  main:
#    container_name: main
#    build:
#      context: .
#    env_file:
#      - .env
#    volumes:
#      - .:/app
#      - /app/node_modules
#    ports:
#      - '${PORT}:${PORT}'
#    command: sh -c "npm run db:migrate; npm run seed; npm run start"
#    depends_on:
#      - postgres
#      - redis
#    restart: always

volumes:
  pgdata: